<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContentPagesTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('content_pages')->insert([

            [
                'title' => 'Replacement and Installation of Electrical Components',
                'excerpt' => '<p>We specialize in replacing and installing crucial electrical components, including circuit breakers and protection relays, to ensure safe yacht operation.</p>',
                'page_text' => '<p>Our expert team specializes in the replacement and installation of essential electrical components such as circuit breakers and protection relays. These components are vital for ensuring the safety and reliable operation of your yacht\'s electrical system. By performing precise installations and upgrades, we help maintain optimal performance and safety standards, minimizing the risks associated with electrical failures while enhancing your boating experience.</p>',
                'seo_title' => 'Professional Replacement and Installation of Electrical Components for Yachts',
                'seo_meta_description' => 'Ensure your yacht\'s safety and performance with our expert replacement and installation services for electrical components, including circuit breakers and protection relays.',
                'seo_slug' => 'replacement-installation-electrical-components',
                'slug' => 'replacement-installation-electrical-components',
            ],
            [
                'title' => 'Installation and Configuration of Battery Management Systems',
                'excerpt' => '<p>We provide expert installation and configuration of battery management systems, incorporating temperature sensors and inverters for optimal battery performance.</p>',
                'page_text' => '<p>The installation and configuration of battery management systems are crucial for maximizing battery performance on your vessel. This service involves integrating temperature sensors, inverters, and advanced connection systems, ensuring optimal charging and discharging cycles while monitoring battery health. Proper management not only extends battery life but also enhances overall energy efficiency onboard, making it essential for yacht owners looking to maintain sustainable and reliable power sources for their marine equipment.</p>',
                'seo_title' => 'Expert Installation and Configuration of Battery Management Systems',
                'seo_meta_description' => 'Optimize your yacht\'s battery performance with our expert installation and configuration of battery management systems, including temperature sensors and inverters for enhanced efficiency.',
                'seo_slug' => 'installation-and-configuration-of-battery-management-systems',
                'slug' => 'installation-and-configuration-of-battery-management-systems',
            ],
            [
                'title' => 'Installation and Maintenance of Solar Panels and Regulators',
                'excerpt' => '<p>We provide eco-friendly solar panel installation and maintenance, ensuring optimal energy efficiency for yacht owners.</p>',
                'page_text' => '<p>Our service offers eco-friendly power solutions for yacht owners through expert installation and maintenance of solar panels and regulators. With a focus on maximizing energy efficiency, our team ensures you harness solar power effectively, reducing reliance on traditional energy sources. We provide comprehensive configuration services to optimize your solar setup, allowing for a seamless transition towards sustainable energy. Let us help you sail towards a greener future with reliable solar solutions.</p>',
                'seo_title' => 'Expert Solar Panel Installation and Maintenance for Yachts',
                'seo_meta_description' => 'Discover eco-friendly solar panel installation and maintenance services for yachts. Optimize energy efficiency with our expert solutions tailored for marine power needs.',
                'seo_slug' => 'installation-and-maintenance-of-solar-panels',
                'slug' => 'installation-and-maintenance-of-solar-panels',
            ],
            [
                'title' => 'Installation and Programming of PLCs for Bow Thrusters and Hydraulic Systems',
                'excerpt' => '<p>We provide specialized installation and programming of PLCs for bow thrusters and hydraulic systems, ensuring efficient and precise control of yacht functions.</p>',
                'page_text' => '<p>Our expert services in the installation and programming of Programmable Logic Controllers (PLCs) for bow thrusters and hydraulic systems guarantee precise control and efficient operation. By integrating advanced PLC technology, we enhance your yacht\'s maneuverability and hydraulic functionality, ensuring that critical systems operate seamlessly. This service is essential for yacht owners looking to improve performance and reliability in complex marine environments.</p>',
                'seo_title' => 'Expert Installation and Programming of PLCs for Bow Thrusters and Hydraulic Systems',
                'seo_meta_description' => 'Our expert installation and programming of PLCs enhance the efficiency and control of your yacht\'s bow thrusters and hydraulic systems, ensuring superior performance.',
                'seo_slug' => 'installation-programming-plcs-bow-thrusters-hydraulic-systems',
                'slug' => 'installation-programming-plcs-bow-thrusters-hydraulic-systems',
            ],
            [
                'title' => 'Setup of Starlink, WiFi, LTE, and Satellite Internet Systems',
                'excerpt' => '<p>We provide comprehensive setup services for Starlink, WiFi, LTE, and satellite internet systems, ensuring reliable connectivity at sea.</p>',
                'page_text' => '<p>Our service for the setup of Starlink, WiFi, LTE, and satellite internet systems ensures reliable connectivity at sea. By integrating advanced marine internet solutions, including Starlink, yacht owners can experience seamless internet access regardless of their location. Whether for navigation, communication, or leisure, having dependable internet is essential for modern maritime adventures.</p>',
                'seo_title' => 'Reliable Marine Internet Solutions: Setup Starlink, WiFi, LTE & Satellite Systems',
                'seo_meta_description' => 'Ensure seamless connectivity with our expert setup of Starlink, WiFi, LTE, and satellite internet systems for your marine vessel. Stay connected at sea.',
                'seo_slug' => 'setup-starlink-wifi-lte-satellite-internet-systems',
                'slug' => 'setup-starlink-wifi-lte-satellite-internet-systems',
            ],
            [
                'title' => 'Installation and Setup of NAS, WiFi Repeaters, and Routers',
                'excerpt' => '<p>Ensure seamless internal networks for data storage and internet access across all onboard devices with our installation services for NAS, WiFi repeaters, and routers.</p>',
                'page_text' => '<p>The installation and setup of Network Attached Storage (NAS), WiFi repeaters, and routers are essential for yacht owners seeking seamless internal networks for data storage and efficient internet access. This service ensures that all connected devices onboard can communicate efficiently and securely, providing reliable data backup and fast internet connectivity throughout the vessel. By implementing an optimized network, you can enjoy smooth streaming and easy access to your digital files on the go.</p>',
                'seo_title' => 'Professional NAS, WiFi Repeaters, and Routers Installation Service',
                'seo_meta_description' => 'Optimize your yacht\'s internal network with our expert installation and setup of NAS, WiFi repeaters, and routers, ensuring seamless data storage and internet connectivity across all devices.',
                'seo_slug' => 'installation-setup-nas-wifi-repeaters-routers',
                'slug' => 'installation-setup-nas-wifi-repeaters-routers',
            ],
            [
                'title' => 'Repair and Maintenance of Electrical Discharge Systems and Relays',
                'excerpt' => '<p>We specialize in the repair and maintenance of electrical discharge systems and relays, ensuring proper power flow and protection for critical yacht systems.</p>',
                'page_text' => '<p>Our comprehensive repair and maintenance services for electrical discharge systems and relays ensure the optimal performance and reliability of power flow across all critical systems on your vessel. By addressing potential issues proactively, we help safeguard your yacht’s electrical infrastructure, protecting sensitive equipment from damaging fluctuations and ensuring uninterrupted operation during your voyages.</p>',
                'seo_title' => 'Expert Repair and Maintenance of Electrical Discharge Systems and Relays',
                'seo_meta_description' => 'Ensure optimal power flow and protection with our expert repair and maintenance services for electrical discharge systems and relays. Keep your yacht\'s systems reliable.',
                'seo_slug' => 'repair-maintenance-electrical-discharge-systems-relays',
                'slug' => 'repair-maintenance-electrical-discharge-systems-relays',
            ],
            [
                'title' => 'Installation of Alarms, Sensors, and Monitoring Systems',
                'excerpt' => '<p>We offer specialized installation services for alarms, sensors, and monitoring systems, including 3-bank battery monitors and bilge alarms, ensuring optimal safety and performance for your yacht.</p>',
                'page_text' => '<p>Our installation services for alarms, sensors, and monitoring systems provide comprehensive solutions tailored to enhance maritime safety. We offer high-quality installations of 3-bank battery monitors, bilge alarms, and shore failure alarms to ensure your vessel remains secure. These systems help monitor critical aspects of your yacht\'s performance and provide alerts for potential issues, giving peace of mind to yacht owners and operators.</p>',
                'seo_title' => 'Expert Installation of Alarms, Sensors & Monitoring Systems for Yachts',
                'seo_meta_description' => 'Ensure your yacht\'s safety with professional installation of alarms, sensors, and monitoring systems. Offering comprehensive solutions like bilge alarms and 3-bank battery monitors.',
                'seo_slug' => 'installation-of-alarms-sensors-monitoring-systems',
                'slug' => 'installation-of-alarms-sensors-monitoring-systems',
            ],
            [
                'title' => 'Setup and Configuration of Entertainment Systems (Bose, Apple TV, TVs)',
                'excerpt' => '<p>We provide expert setup and configuration of entertainment systems like Bose, Apple TV, and TVs for an unparalleled onboard audio and video experience.</p>',
                'page_text' => '<p>Our service for the setup and configuration of entertainment systems, including top brands like Bose and Apple TV, ensures you enjoy the pinnacle of onboard audio and video experiences. Our expert technicians will seamlessly integrate all components, including TVs, delivering high-quality sound and visuals for your leisure. Tailored to your preferences, this service transforms your yacht into a luxurious entertainment hub, enhancing your enjoyment at sea.</p>',
                'seo_title' => 'Expert Setup and Configuration of Marine Entertainment Systems',
                'seo_meta_description' => 'Transform your yacht with professional setup and configuration of Bose, Apple TV, and TV entertainment systems, ensuring the ultimate onboard audio and video enjoyment.',
                'seo_slug' => 'setup-configuration-entertainment-systems',
                'slug' => 'setup-configuration-entertainment-systems',
            ],
            [
                'title' => 'Installation and Calibration of Marine Navigation Systems',
                'excerpt' => '<p>Expert installation and calibration of marine navigation systems, including plotters, transducers, and radar, for accurate real-time navigation.</p>',
                'page_text' => '<p>Ensure safe and accurate navigation on your vessel with our expert installation and calibration of marine navigation systems. We specialize in integrating plotters, transducers, and radar systems, tailoring the setup to your specific needs. Our team guarantees that your navigation equipment is finely tuned for real-time performance, enhancing your ability to navigate in various conditions while providing you with confidence and peace of mind on the water.</p>',
                'seo_title' => 'Professional Installation and Calibration of Marine Navigation Systems',
                'seo_meta_description' => 'Get expert installation and calibration of marine navigation systems, including plotters, transducers, and radar systems for accurate real-time navigation on your vessel.',
                'seo_slug' => 'installation-and-calibration-of-marine-navigation-systems',
                'slug' => 'installation-and-calibration-of-marine-navigation-systems',
            ],
            [
                'title' => 'Installation of CCTV Remote Monitoring Systems',
                'excerpt' => '<p>Our CCTV remote monitoring system installation service ensures your yacht\'s security with real-time access to onboard cameras from anywhere in the world.</p>',
                'page_text' => '<p>Enhance your vessel\'s security with our professional installation of CCTV remote monitoring systems. This vital service provides full security for your yacht, allowing for real-time access to onboard cameras from anywhere in the world. Whether you\'re at home or traveling, our high-quality surveillance solutions ensure that you can monitor your yacht\'s surroundings and safeguard your investments with ease and convenience.</p>',
                'seo_title' => 'CCTV Remote Monitoring Systems Installation for Yachts',
                'seo_meta_description' => 'Secure your yacht with our CCTV remote monitoring systems installation service, ensuring real-time access to onboard cameras from anywhere in the world.',
                'seo_slug' => 'cctv-remote-monitoring-systems-installation',
                'slug' => 'cctv-remote-monitoring-systems-installation',
            ],
            [
                'title' => 'Setup and Configuration of AI-Powered Offline Servers',
                'excerpt' => '<p>We configure AI-powered offline servers to assist with daily tasks and provide immediate access to equipment manuals onboard.</p>',
                'page_text' => '<p>Our service for the setup and configuration of AI-powered offline servers ensures that yacht owners can effectively manage daily tasks onboard. These advanced systems provide immediate access to equipment manuals and troubleshooting assistance without relying on internet connectivity, enhancing the efficiency and autonomy of maritime operations. By integrating AI technology, we help streamline processes, making your onboard experience smoother and more enjoyable.</p>',
                'seo_title' => 'AI-Powered Offline Servers Setup for Efficient Yacht Operations',
                'seo_meta_description' => 'Expert setup and configuration of AI-powered offline servers for yachts, providing instant access to equipment manuals and enhancing daily operations without internet dependency.',
                'seo_slug' => 'ai-powered-offline-servers-setup',
                'slug' => 'ai-powered-offline-servers-setup',
            ],
            [
                'title' => 'Installation and Repair of Bow Thrusters and Stabilizer Systems',
                'excerpt' => '<p>We specialize in the installation and repair of bow thrusters and stabilizer systems, enhancing vessel stability and maneuverability for safer navigation.</p>',
                'page_text' => '<p>Our installation and repair services for bow thrusters and stabilizer systems are essential for maintaining vessel stability and control, ensuring smoother operations on the water. These systems enhance maneuverability and comfort during navigation, making them critical components for both recreational and commercial yachts. Our expert technicians are trained to provide precise installation and reliable repairs, ensuring your vessel performs optimally while maximizing safety and efficiency.</p>',
                'seo_title' => 'Bow Thruster and Stabilizer System Installation & Repair',
                'seo_meta_description' => 'Professional installation and repair of bow thrusters and stabilizer systems to ensure vessel stability, control, and smoother operations at sea.',
                'seo_slug' => 'bow-thruster-stabilizer-installation-repair',
                'slug' => 'bow-thruster-stabilizer-installation-repair',
            ],
            [
                'title' => 'Installation of Lighting and Inspection Systems',
                'excerpt' => '<p>We provide expert installation of lighting and inspection systems, enhancing visibility and safety for your vessel.</p>',
                'page_text' => '<p>The installation of lighting and inspection systems on your vessel is crucial for both safety and functionality. From internal cabin lighting that enhances comfort to navigation lights that ensure visibility on the water, our expert services help secure your yacht during nighttime operations. Properly installed lighting systems not only improve the aesthetic value of your boat but also comply with maritime safety regulations, providing peace of mind for all aboard.</p>',
                'seo_title' => 'Expert Installation of Lighting and Inspection Systems for Yachts',
                'seo_meta_description' => 'Ensure safety and visibility on your yacht with our professional installation of lighting and inspection systems, including cabin lighting and navigation lights.',
                'seo_slug' => 'installation-of-lighting-and-inspection-systems',
                'slug' => 'installation-of-lighting-and-inspection-systems',
            ],
            [
                'title' => 'Custom Electronic PCB Designs',
                'excerpt' => '<p>We offer tailored PCB solutions to meet your specific electronic needs onboard, ensuring optimal performance and reliability.</p>',
                'page_text' => '<p>Our custom electronic PCB design services provide tailored solutions for specific electronic needs onboard your vessel. With a focus on optimizing performance and reliability, our expert engineers collaborate with you to design printed circuit boards that meet the unique demands of marine environments. From concept to prototype, we ensure that every PCB is crafted with precision, addressing your electrical challenges while adhering to stringent safety standards.</p>',
                'seo_title' => 'Custom Electronic PCB Designs for Marine Applications',
                'seo_meta_description' => 'Discover our expert custom electronic PCB design services tailored for marine environments. Enhance your vessel\'s performance with bespoke solutions.',
                'seo_slug' => 'custom-electronic-pcb-designs',
                'slug' => 'custom-electronic-pcb-designs',
            ],
            [
                'title' => 'Design and 3D Printing of Parts in Plastics or Metals',
                'excerpt' => '<p>We provide custom 3D printed parts in plastics and metals, tailored to meet the specific needs of your onboard systems.</p>',
                'page_text' => '<p>We offer custom 3D printed parts for any onboard solution, utilizing a variety of materials including durable plastics and high-performance metals. Our advanced design process ensures precision and quality, catering to the unique needs of yacht owners and marine service providers. Whether you require a replacement component or a bespoke part for your marine equipment, our 3D printing capabilities can provide efficient and reliable solutions to enhance your vessel\'s functionality.</p>',
                'seo_title' => 'Design and 3D Printing of Marine Parts in Plastics and Metals',
                'seo_meta_description' => 'Discover our custom 3D printing services for marine electronic parts, available in a range of materials including plastics and metals, designed for optimal performance on your yacht.',
                'seo_slug' => 'design-3d-printing-parts-plastics-metals',
                'slug' => 'design-3d-printing-parts-plastics-metals',
            ],
            [
                'title' => 'Design and Laser Cutting of Plexiglass and Wooden Parts',
                'excerpt' => '<p>We provide precision laser cutting of plexiglass and custom wooden components, ensuring high-quality, tailored designs for marine applications.</p>',
                'page_text' => '<p>Our service offers precision laser cutting of plexiglass up to 20mm in thickness, along with custom fabrication of wooden components. Utilizing state-of-the-art technology, we ensure accurate designs that meet your specific requirements. Whether you\'re looking to create sleek windows, unique display pieces, or functional parts for your marine applications, our tailored solutions enhance both aesthetics and functionality for your vessel.</p>',
                'seo_title' => 'Precision Laser Cutting Services for Plexiglass and Wood',
                'seo_meta_description' => 'Explore our precision laser cutting services for plexiglass and custom wooden parts, tailored for yacht owners and marine service providers. Enhance your vessel\'s design today.',
                'seo_slug' => 'design-laser-cutting-plexiglass-wooden-parts',
                'slug' => 'design-laser-cutting-plexiglass-wooden-parts',
            ],
            [
                'title' => 'Repair of Sound Systems, Subwoofers, and Audio Setups',
                'excerpt' => '<p>We provide comprehensive repair services for sound systems, subwoofers, and audio setups, ensuring top-notch onboard audio experiences.</p>',
                'page_text' => '<p>Our expert repair services for sound systems, subwoofers, and audio setups ensure flawless onboard audio experiences. Whether you\'re facing issues with connectivity, sound quality, or equipment malfunction, our skilled technicians utilize advanced diagnostic tools to identify and resolve problems efficiently. We understand the importance of high-quality audio for entertainment on the water and provide prompt, reliable service to restore your marine audio systems to peak performance.</p>',
                'seo_title' => 'Expert Repair of Marine Sound Systems and Audio Setups',
                'seo_meta_description' => 'Discover professional repair services for sound systems, subwoofers, and audio setups, ensuring flawless onboard audio experiences for yacht owners.',
                'seo_slug' => 'repair-sound-systems-subwoofers-audio-setups',
                'slug' => 'repair-sound-systems-subwoofers-audio-setups',
            ],
            [
                'title' => 'Global Sourcing of Electrical, Electronic, and IT Materials',
                'excerpt' => '<p>We source and deliver high-quality electrical, electronic, and IT materials from around the globe, ensuring the best components for your marine needs.</p>',
                'page_text' => '<p>We specialize in sourcing and delivering high-quality electrical, electronic, and IT-related materials from reputable suppliers worldwide. Our extensive network ensures that yacht owners and marine service providers receive the best components and materials tailored to their needs, regardless of location. Trust us to provide reliable solutions, optimizing your vessel\'s performance with top-tier products.</p>',
                'seo_title' => 'Global Sourcing of Electrical and Electronic Materials for Marine',
                'seo_meta_description' => 'Discover our global sourcing service for top-quality electrical, electronic, and IT materials tailored for yacht owners and marine professionals. Get the best components delivered to your location.',
                'seo_slug' => 'global-sourcing-electrical-electronic-materials',
                'slug' => 'global-sourcing-electrical-electronic-materials',
            ],
            [
                'title' => 'Installation of Control Systems for Water Valves and Tank Monitoring',
                'excerpt' => '<p>We provide expert installation of control systems for managing water flow and monitoring tank levels, ensuring optimal vessel operations.</p>',
                'page_text' => '<p>Our installation service for control systems focuses on managing the flow of water and monitoring tank levels to ensure optimal operations on your vessel. Equipped with advanced technology, we install reliable control systems that enhance efficiency, conserve water, and enable effortless monitoring for yacht owners. With our expert services, you can effectively manage water resources and ensure the proper functioning of the tank systems on board.</p>',
                'seo_title' => 'Control Systems Installation for Water Valves and Tank Monitoring | Marine Electronics',
                'seo_meta_description' => 'Expert installation of control systems for water valves and tank monitoring. Enhance your vessel’s operations and manage water resources effectively with our marine electronics service.',
                'seo_slug' => 'installation-control-systems-water-valves-tank-monitoring',
                'slug' => 'installation-control-systems-water-valves-tank-monitoring',
            ],
            [
                'title' => 'Installation of CCTV Remote Monitoring Systems',
                'excerpt' => '<p>Secure your yacht with our CCTV remote monitoring systems for real-time access to onboard cameras from any location globally.</p>',
                'page_text' => '<p>Enhance your yacht\'s security with our professional installation of CCTV remote monitoring systems. These advanced systems provide full surveillance with real-time access to onboard cameras from anywhere in the world. Whether you are at home or traveling abroad, you can effortlessly monitor your vessel, ensuring its safety against unauthorized access or incidents. Our expert technicians ensure a seamless setup, allowing you peace of mind knowing your yacht is protected 24/7.</p>',
                'seo_title' => 'CCTV Remote Monitoring System Installation for Yachts',
                'seo_meta_description' => 'Ensure your yacht\'s security with professional installation of CCTV remote monitoring systems, providing real-time camera access from anywhere in the world.',
                'seo_slug' => 'cctv-remote-monitoring-system-installation',
                'slug' => 'cctv-remote-monitoring-system-installation',
            ],
        ]);
    }
}
